version: '2'
services:
  web:
    build: ./builds/web
    stdin_open: true
    container_name: web
    volumes:
      - ../front-end:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  app:
    build: ./builds/app/
    container_name: app
    hostname: app
    ports:
      - "8078:80"
    links:
      - redis.app
      - mongo
    volumes:
      - ../back-end:/app
    environment:
      - REDIS_URL=redis://redis.app
  redis.app:
    image: redis:3.2.10
    hostname: redis.app
    container_name: redis.app
  commander.redis.app:
    image: rediscommander/redis-commander:latest
    hostname: commander.redis.app
    container_name: commander.redis.app
    command: /redis-commander/docker/entrypoint.sh
    environment:
      - REDIS_HOSTS=redis.app
    links:
      - redis.app
    ports:
      - "8084:8081"
  mongo:
    container_name: mongo
    image: mongo
    hostname: mongo
    ports:
      - "27017:27017"
  mongoexpress:
    image: mongo-express
    hostname: mongo-express
    links:
      - mongo:mongo
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo

